[package]
name = "master-mind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.1"
strum = "0.26"
strum_macros = "0.26"
rand = "0.8.5"
crossterm = "0.27"
